name: WDIO tests
run-name: ${{ github.actor }} is executing the pipeline...

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: luisrain/wdio-framework:1.0.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    timeout-minutes: 30
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g
    env:
      WDIO_HOST: localhost
    steps:
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Create env file
        run: echo "${{ vars.ENV }}" > .env   
      - name: Running Tests
        run: npm run wdio
